version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: warehouse_postgres
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "listen_addresses=*"]  # явное указание

volumes:
  postgres_data: